import {
  LayoutDashboard,
  MapPin,
  Zap,
  History,
  Wallet,
  Receipt,
  ShoppingBag,
  Users,
  Bell,
  UserCircle,
  Truck,
  BarChart3,
  FileText,
  PlugZap,
  CalendarClock,
  DollarSign,
  Wrench,
  ClipboardList,
  Building2,
  Store,
  Settings,
  PieChart,
} from 'lucide-react'

export const ROLE_META = {
  driver: { label: 'EV Driver', home: '/driver' },
  fleet: { label: 'Fleet Manager', home: '/fleet' },
  operator: { label: 'Station Operator', home: '/operator' },
  technician: { label: 'Technician', home: '/technician' },
  admin: { label: 'Admin', home: '/admin' },
}

export const NAV = {
  driver: [
    { to: '/driver', label: 'Dashboard', icon: LayoutDashboard, end: true },
    { to: '/driver/stations', label: 'Charging Stations', icon: MapPin },
    { to: '/driver/session', label: 'Active Session', icon: Zap },
    { to: '/driver/history', label: 'Charging History', icon: History },
    { to: '/driver/wallet', label: 'Wallet', icon: Wallet },
    { to: '/driver/transactions', label: 'Transactions', icon: Receipt },
    { to: '/driver/marketplace', label: 'Marketplace', icon: ShoppingBag },
    { to: '/driver/community', label: 'Community', icon: Users },
    { to: '/driver/notifications', label: 'Notifications', icon: Bell },
    { to: '/driver/profile', label: 'Profile', icon: UserCircle },
  ],
  fleet: [
    { to: '/fleet', label: 'Dashboard', icon: LayoutDashboard, end: true },
    { to: '/fleet/vehicles', label: 'Fleet Vehicles', icon: Truck },
    { to: '/fleet/analytics', label: 'Analytics', icon: BarChart3 },
    { to: '/fleet/billing', label: 'Billing', icon: FileText },
  ],
  operator: [
    { to: '/operator', label: 'Dashboard', icon: LayoutDashboard, end: true },
    { to: '/operator/stations', label: 'Stations', icon: Building2 },
    { to: '/operator/chargers', label: 'Chargers', icon: PlugZap },
    { to: '/operator/reservations', label: 'Reservations', icon: CalendarClock },
    { to: '/operator/revenue', label: 'Revenue', icon: DollarSign },
  ],
  technician: [
    { to: '/technician', label: 'Dashboard', icon: LayoutDashboard, end: true },
    { to: '/technician/tickets', label: 'Assigned Tickets', icon: ClipboardList },
    { to: '/technician/history', label: 'Maintenance History', icon: Wrench },
  ],
  admin: [
    { to: '/admin', label: 'Dashboard', icon: LayoutDashboard, end: true },
    { to: '/admin/users', label: 'Users', icon: Users },
    { to: '/admin/stations', label: 'Stations', icon: Building2 },
    { to: '/admin/marketplace', label: 'Marketplace', icon: Store },
    { to: '/admin/reports', label: 'Reports', icon: FileText },
    { to: '/admin/analytics', label: 'Analytics', icon: PieChart },
    { to: '/admin/settings', label: 'Settings', icon: Settings },
  ],
}
